### PR TITLE
Add first public version

### PR DESCRIPTION
**Pull request by JinneeJ**
This PR adds implementation of first public version of Ktlint IDEA Reporter. This [reporter](https://github.com/pinterest/ktlint#creating-a-reporter) improves [ktlint](https://github.com/pinterest/ktlint) output for better integration with IntelliJ IDEA based IDE.

The main goal is to use it in gradle task for our future public ktlint gradle plugin.

### CODE REVIEW

**Review by bmoliveira — COMMENTED** [review]
This is an outstanding contribution to open source! Nice initiative 🚀

I only have two questions:

- The `gradle-wrapper.jar` is empty. Is it on purpose?
- Current publications are only configured with staging, right?

**Comment by JinneeJ** [comment]
Thanks a lot for the review! 

> The gradle-wrapper.jar is empty. Is it on purpose?

I don't know how it happened 😅 I've updated [commit](https://github.com/Doist/ktlint-idea-reporter/pull/1/commits/6f9b03e22e056d46908e4a25d2a42600215b3748) with adding proper jar file.

> Current publications are only configured with staging, right?

I didn't test it yet, but I used github action from https://github.com/Doist/doistx-normalize as an example. If it won't work during testing, I'll update it in another PR. Would it work? :)

**Review by bmoliveira — APPROVED** [review]
Perfect everything is looking good 🚀

**Comment by JinneeJ** [comment]
Thanks again for the review! Release was done after several attempts (artifacts might appear later) with following modifications.

- Added JavaDoc jar file as it's needed for publishing into maven central
- Also increased memory for gradle. Probably needed for Dokka :)

(Also thanks @goncalossilva for the help with maven central publishing)

**Pull request merged**
